parameters:
  - name: suite
    type: string
  - name: browser
    type: string
  - name: postDeploy
    type: boolean
    default: false

jobs:
  - job: ${{ format('{0}_{1}', parameters.suite, parameters.browser) }}
    displayName: 'Run @${{ parameters.suite }} on ${{ parameters.browser }}'
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: 8.0.x

      - script: |
          mkdir -p $(ArtifactRoot)/Reports
          mkdir -p $(ArtifactRoot)/Screenshots
          mkdir -p $(ArtifactRoot)/Logs
          mkdir -p $(ArtifactRoot)/TestResults
          mkdir -p $(ArtifactRoot)/Metrics
        displayName: 'Prepare evidence folders'

      - task: DotNetCoreCLI@2
        displayName: 'Execute SpecFlow tests'
        inputs:
          command: test
          projects: '$(TestProject)'
          arguments: >
            --configuration $(BuildConfiguration)
            --logger trx
            --logger "console;verbosity=detailed"
            --results-directory $(ArtifactRoot)/TestResults/${{ parameters.suite }}-${{ parameters.browser }}
            --collect:"XPlat Code Coverage"
            --filter "TestCategory=${{ parameters.suite }}"
        env:
          TestSettings__Browser: '${{ parameters.browser }}'
          TestSettings__Headless: 'true'
          TestSettings__CaptureScreenshotsOnFailure: 'true'
          TestSettings__EnableVideo: 'false'

      - task: PowerShell@2
        displayName: 'Collect metrics JSON'
        inputs:
          targetType: inline
          script: |
            $trxCount = (Get-ChildItem "$(ArtifactRoot)/TestResults/${{ parameters.suite }}-${{ parameters.browser }}" -Filter *.trx -Recurse | Measure-Object).Count
            $metrics = @{
              suite = "${{ parameters.suite }}"
              browser = "${{ parameters.browser }}"
              buildId = "$(Build.BuildId)"
              executionTimeUtc = (Get-Date).ToUniversalTime().ToString('o')
              trxFiles = $trxCount
              flakyRate = 0
              successRate = 0
            }
            $metrics | ConvertTo-Json | Out-File "$(ArtifactRoot)/Metrics/${{ parameters.suite }}-${{ parameters.browser }}.json"

      - publish: $(ArtifactRoot)
        artifact: evidence-${{ parameters.suite }}-${{ parameters.browser }}
        condition: always()
